# Configuration for efm-langserver.
#
# Usually this is at ~/.config/efm-langserver/config.yaml, but here it is bundled with the vim
# configs, as ~/.vim/efm-langserver-config.yaml. See also lsp.vim.
#
# Example install command is provided for tools.

version: 2

# Tags-based definition is turned off, because it's not needed here and could cause duplicate
# results.
provide-definition: false

tools:

  json-prettier: &json-prettier
    # npm install -g prettier
    format-command: 'prettier --parser json'

  json-jq: &json-jq
    # apt-get install jq
    lint-command: 'jq .'

  python-flake8: &python-flake8
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  python-mypy: &python-mypy
    lint-command: 'mypy --follow-imports=silent --show-column-numbers'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  rst-pandoc: &rst-pandoc
    format-command: 'pandoc -f rst -t rst -s --columns=79'

  rst-lint: &rst-lint
    lint-command: 'rst-lint'
    lint-formats:
      - '%tNFO %f:%l %m'
      - '%tARNING %f:%l %m'
      - '%tRROR %f:%l %m'
      - '%tEVERE %f:%l %m'

  sh-shellcheck: &sh-shellcheck
    # apt-get install shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  yaml-prettier: &yaml-prettier
    # npm install -g prettier
    format-command: 'prettier --parser yaml'

languages:

  json:
    - <<: *json-prettier
    - <<: *json-jq

  python:
    - <<: *python-flake8
    - <<: *python-mypy

  rst:
    - <<: *rst-lint
    - <<: *rst-pandoc

  sh:
    - <<: *sh-shellcheck

  yaml:
    - <<: *yaml-prettier
