# Configuration for efm-langserver.
#
# Usually this is at ~/.config/efm-langserver/config.yaml, but here it is bundled with the vim
# configs, as ~/.vim/efm-langserver-config.yaml. See also lsp.vim.
#
# Example install command is provided for tools.

version: 2

tools:

  json-prettier: &json-prettier
    # npm install -g prettier
    format-command: 'prettier --parser json'

  json-jq: &json-jq
    # apt-get install jq
    lint-command: 'jq .'

  python-flake8: &python-flake8
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  python-mypy: &python-mypy
    lint-command: 'mypy --follow-imports=silent --show-column-numbers'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  sh-shellcheck: &sh-shellcheck
    # apt-get install shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

languages:

  json:
    - <<: *json-prettier
    - <<: *json-jq

  python:
    - <<: *python-flake8
    - <<: *python-mypy

  sh:
    - <<: *sh-shellcheck
